
# Variables

@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/room

###

# Create room
# @name createRoom
POST {{baseUrl}}/room
Accept: application/json
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/room/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/room/fd5c1498-14e4-443f-9ae4-d9f486f7c454/questions
Accept: application/json
Content-Type: application/json

{
    "question": "O que é Flutter?"
}